cookie:
  expiry_days: 30
  key: signature_key
  name: mortgage_cookie
credentials:
  usernames:
    Chepet:
      name: Chepet Luke
      password: $pbkdf2-sha256$29000$hTBGKAWgVIpRKiXEOGcMwQ$mBlLL.vFpmub5sKe0Iea9XAB5xM/e6YvpKBgQUfkYK4
    Doreen:
      name: Doreen Machoni
      password: $pbkdf2-sha256$29000$Pud8by0FIMS4txZiDKEUQg$ez5yAsA9uPYi/ufBHiGdkcLo7wn.UjHMeX4kFkPtV3I
    Jacky:
      name: Jacky Peter
      password: $pbkdf2-sha256$29000$vldqbU3JuZeSknLuHWOslQ$t0rn5PEL2SrBbO05AP/yXl9cDneiwIdZksr64rXCs38
    Ochieng:
      name: Fredrick Ochieng
      password: $pbkdf2-sha256$29000$0NpbS8k5B0DIGSMEwPifsw$dd3Fzqt5y9urazutmpuFNjQItMl//LJV4XnVbqZjLg4
