cookie:
  expiry_days: 30
  key: signature_key
  name: mortgage_cookie
credentials:
  usernames:
    Jane:
      name: Jane Apodi
      password: $pbkdf2-sha256$29000$JcS413oPQciZs5ZSynlP6Q$HSqNM/uTp3MH31xoO3nJc0mgnxcuAuPwJV5eZgGUyxs
    Sakawa:
      name: Sakawa Bob
      password: $pbkdf2-sha256$29000$Z.w9Z0xp7X2vdY5xbi3l/A$0Tre/prZoy6avVzvQ5zrEKDbDPWfglhUH8MLTf4wWrU
